name: Publish Plugin

permissions:
    contents: write
    deployments: write
    packages: write

on:
    push:
        paths:
            - 'apps/wp-plugin/**'
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache yarn cache
              id: yarn-cache
              uses: actions/cache@v4
              with:
                  path: |
                      .nx
                      .yarn/cache
                      **/node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn --immutable

            - name: Bump version
              run: |
                  cd apps/wp-plugin
                  yarn bump-version
                  git push

            - name: Setup Subversion
              run: |
                  sudo apt-get update
                  sudo apt-get install subversion

            - name: Export to SVN
              run: |
                  PLUGIN_SLUG=elm-users-tracking
                  SVN_REPO="https://plugins.svn.wordpress.org/$PLUGIN_SLUG/"
                  CURRENT_VERSION=$(node -p -e "require('./apps/wp-plugin/package.json').version")
                  SVN_DIR=svn-wordpress

                  svn checkout $SVN_REPO $SVN_DIR

                  rsync -r --delete --exclude='.svn' ./apps/wp-plugin/ $SVN_DIR/trunk/
                  rsync -r --delete --exclude='.svn' ./apps/wp-plugin/ $SVN_DIR/trunk/

                  cd $SVN_DIR
                  svn propset svn:ignore -RF .svnignore .
                  svn add --force * --auto-props --parents --depth infinity -q
                  svn ci -m "Update to version $CURRENT_VERSION" --username ${{ secrets.WP_SVN_USERNAME }} --password ${{ secrets.WP_SVN_PASSWORD }}

                  svn cp trunk tags/$CURRENT_VERSION
                  svn ci -m "Tagging version $CURRENT_VERSION" --username ${{ secrets.WP_SVN_USERNAME }} --password ${{ secrets.WP_SVN_PASSWORD }}
